# CUDA NDT Matcher - Build System

# Cargo config generated by colcon-cargo-ros2
cargo_config := "build/ros2_cargo_config.toml"
manifest := "Cargo.toml"

# Paths for testing
local_setup := "install/setup.bash"
sample_map_dir := "data/sample-map"
sample_rosbag := "data/sample-rosbag-fixed"
rosbag_output_dir := "rosbag"
ground_truth_dir := "tests/fixtures/ground_truth"

# Show available recipes
default:
    @just --list

# Check prerequisites and install build dependencies
setup:
    #!/usr/bin/env bash
    set -e
    echo "Checking prerequisites..."
    MISSING=""

    # Check Rust toolchain
    if ! command -v rustc &> /dev/null; then
        echo "  ERROR: Rust toolchain not found"
        echo "         Install via: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
        MISSING="$MISSING rust"
    else
        echo "  Rust: $(rustc --version)"
    fi

    # Check Rust nightly (for rustfmt)
    if ! rustup run nightly rustc --version &> /dev/null; then
        echo "  WARN: Rust nightly not found (needed for 'just lint')"
        echo "        Install via: rustup toolchain install nightly"
    else
        echo "  Rust nightly: $(rustup run nightly rustc --version 2>/dev/null | head -1)"
    fi

    # Check CUDA toolkit
    if ! command -v nvcc &> /dev/null; then
        echo "  ERROR: CUDA toolkit not found (nvcc)"
        echo "         Install NVIDIA CUDA Toolkit"
        MISSING="$MISSING cuda"
    else
        echo "  CUDA: $(nvcc --version | grep release | sed 's/.*release //' | sed 's/,.*//')"
    fi

    # Check ROS Humble
    if [[ ! -f /opt/ros/humble/setup.bash ]]; then
        echo "  ERROR: ROS Humble not found at /opt/ros/humble"
        MISSING="$MISSING ros-humble"
    else
        echo "  ROS Humble: /opt/ros/humble"
    fi

    # Check Autoware 1.5.0
    if [[ ! -f /opt/autoware/1.5.0/setup.bash ]]; then
        echo "  ERROR: Autoware 1.5.0 not found at /opt/autoware/1.5.0"
        MISSING="$MISSING autoware"
    else
        echo "  Autoware 1.5.0: /opt/autoware/1.5.0"
    fi

    # Check GNU Parallel (used by run_demo.sh)
    if ! command -v parallel &> /dev/null; then
        echo "  ERROR: GNU Parallel not found"
        echo "         Install via: sudo apt install parallel"
        MISSING="$MISSING parallel"
    else
        echo "  GNU Parallel: $(parallel --version | head -1)"
    fi

    # Check direnv (optional but recommended)
    if ! command -v direnv &> /dev/null; then
        echo "  WARN: direnv not found (optional, recommended for environment setup)"
        echo "        Install via: sudo apt install direnv"
    else
        echo "  direnv: $(direnv --version)"
    fi

    # Exit if required dependencies are missing
    if [[ -n "$MISSING" ]]; then
        echo ""
        echo "ERROR: Missing required dependencies:$MISSING"
        exit 1
    fi

    # Install Python dependencies
    echo ""
    echo "Installing Python build dependencies..."
    pip install -U colcon-cargo-ros2

    echo ""
    echo "Setup complete!"

# Build all packages with colcon (only check src/ directory)
build:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release

# Clean all build artifacts
clean:
    rm -rf build install log target

# Format code with rustfmt
format:
    cargo +nightly fmt --manifest-path {{manifest}} --all

# Check formatting and run clippy on all crates
lint:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} --all
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} --all-targets

# Lint ndt_cuda crate only
lint-ndt-cuda:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} -p ndt_cuda
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} -p ndt_cuda

# Lint cuda_ffi crate only
lint-cuda-ffi:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} -p cuda_ffi
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ffi

# Lint cuda_ndt_matcher crate only
lint-cuda-ndt-matcher:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo +nightly fmt --check --manifest-path {{manifest}} -p cuda_ndt_matcher
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ndt_matcher

# Run all Rust unit tests
test-rust:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test \
        --manifest-path {{manifest}} \
        --config {{cargo_config}} \
        --all-targets

# Test ndt_cuda crate only
test-ndt-cuda:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test \
        --manifest-path {{manifest}} \
        --config {{cargo_config}} \
        -p ndt_cuda

# Test cuda_ffi crate only
test-cuda-ffi:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ffi

# Test cuda_ndt_matcher crate only
test-cuda-ndt-matcher:
    #!/usr/bin/env bash
    source {{local_setup}}
    cargo test --manifest-path {{manifest}} --config {{cargo_config}} -p cuda_ndt_matcher

# Run Rust unit tests only (fast)
test: test-rust

# Run all tests including integration tests (slow, requires sample data)
test-all: test-rust test-integration

# Run Python integration tests (prepares data if needed)
test-integration: ensure-test-data
    #!/usr/bin/env bash
    set -eo pipefail
    cd "$(dirname {{manifest}})"

    # Check if pytest is available
    if ! command -v pytest &> /dev/null; then
        echo "pytest not found. Install with: pip install -r tests/requirements.txt"
        exit 1
    fi

    # Run integration tests
    pytest tests/test_cuda_ndt.py -v

# Ensure test data is available (idempotent)
ensure-test-data: ensure-sample-data ensure-ground-truth

# Download sample data if not present (idempotent)
ensure-sample-data:
    #!/usr/bin/env bash
    set -eo pipefail
    if [[ -d "{{sample_map_dir}}" && -d "{{sample_rosbag}}" ]]; then
        echo "Sample data already exists, skipping download"
    else
        echo "Downloading sample data..."
        ./scripts/download_sample_data.sh
    fi

# Collect ground truth if not present (idempotent)
ensure-ground-truth: ensure-sample-data
    #!/usr/bin/env bash
    set -eo pipefail
    if [[ -d "{{ground_truth_dir}}/rosbag" ]]; then
        echo "Ground truth already exists, skipping collection"
    else
        echo "Collecting ground truth data..."
        ./scripts/collect_ground_truth.sh
    fi

# Force re-collection of ground truth
refresh-ground-truth: ensure-sample-data
    #!/usr/bin/env bash
    set -eo pipefail
    echo "Refreshing ground truth data..."
    rm -rf \
        "{{ground_truth_dir}}/rosbag" \
        "{{ground_truth_dir}}/debug.jsonl" \
        "{{ground_truth_dir}}/metadata.json"
    ./scripts/collect_ground_truth.sh

# Run all quality checks (lint + test)
quality: lint test

# Download sample map and rosbag data
download-data:
    ./scripts/download_sample_data.sh

play-rosbag:
    #!/usr/bin/env bash
    set -eo pipefail
    ros2 bag play -l $(realpath {{sample_rosbag}})

# Start Autoware builtin NDT demo (delegates to tests/comparison)
run-builtin:
    cd tests/comparison && just run

# Start CUDA NDT demo (simulation + rosbag + recording)
run-cuda:
    ./scripts/run_demo.sh --cuda \
        "$(realpath {{sample_map_dir}})" \
        "$(realpath {{sample_rosbag}})" \
        "{{rosbag_output_dir}}"

# Enable NDT matching via service call
enable-ndt:
    #!/usr/bin/env bash
    ros2 service call \
        /localization/pose_estimator/trigger_node_srv \
        std_srvs/srv/SetBool \
        "{data: true}"

# Monitor NDT pose output
monitor-ndt:
    #!/usr/bin/env bash
    ros2 topic echo /localization/pose_estimator/pose_with_covariance

# === Profiling ===

# Profile all NDT modes (builtin, cuda-cpu, cuda-gpu)
profile-all:
    ./scripts/profile_ndt.sh --modes builtin,cuda-cpu,cuda-gpu

# Profile GPU modes only (faster)
profile-gpu:
    ./scripts/profile_ndt.sh --modes builtin,cuda-gpu

# Profile with perf CPU sampling (requires sudo)
profile-perf:
    ./scripts/profile_ndt.sh --modes builtin,cuda-gpu --perf

# Profile with nsys GPU profiling
profile-nsys:
    ./scripts/profile_ndt.sh --modes cuda-gpu --nsys

# Analyze existing profile results
analyze-profile dir:
    python3 ./scripts/analyze_profile.py {{dir}}

# Run CUDA NDT in CPU mode (for comparison)
run-cuda-cpu:
    NDT_USE_GPU=0 \
        ./scripts/run_demo.sh --cuda \
        "$(realpath {{sample_map_dir}})" \
        "$(realpath {{sample_rosbag}})" \
        "{{rosbag_output_dir}}"

# === Comparison Testing ===

# Build patched Autoware for comparison (required for debug output)
build-comparison:
    cd tests/comparison && just build

# Clean comparison build artifacts
clean-comparison:
    cd tests/comparison && just clean

# === Debug Data Collection ===

# Log output directory
logs_dir := "logs"

# --- Build Recipes (Selective Debug Features) ---

# Build CUDA with all debug features enabled
build-cuda-debug:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features debug

# Build CUDA with per-iteration debug only (JSONL output)
build-cuda-debug-iterations:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features debug-output

# Build CUDA with voxel dump only
build-cuda-debug-voxels:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features debug-voxels

# Build CUDA with voxel-per-point tracking only (ndt_cuda feature)
build-cuda-debug-vpp:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release -p ndt_cuda --features debug-vpp

# Build CUDA with GPU vs CPU covariance comparison only (ndt_cuda feature)
build-cuda-debug-cov:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release -p ndt_cuda --features debug-cov

# Build CUDA with profiling (timing + JSONL output, minimal overhead)
# Uses debug-output for JSONL but without full debug-iteration data collection
build-cuda-profiling:
    #!/usr/bin/env bash
    colcon build \
        --base-paths src \
        --symlink-install \
        --cmake-args -DCMAKE_BUILD_TYPE=Release \
        --cargo-args --release --features profiling,debug-output

# --- Run Recipes (Selective Debug Features) ---

# Run CUDA with all debug output (per-iteration data, profiling timing, voxel dump)
run-cuda-debug: build-cuda-debug
    mkdir -p {{logs_dir}}
    NDT_DEBUG_FILE={{logs_dir}}/ndt_cuda_debug.jsonl \
    NDT_DUMP_VOXELS_FILE={{logs_dir}}/ndt_cuda_voxels.json \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Run CUDA with per-iteration debug only (JSONL output)
run-cuda-debug-iterations: build-cuda-debug-iterations
    mkdir -p {{logs_dir}}
    NDT_DEBUG_FILE={{logs_dir}}/ndt_cuda_debug.jsonl \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Run CUDA with voxel dump only
run-cuda-debug-voxels: build-cuda-debug-voxels
    mkdir -p {{logs_dir}}
    NDT_DUMP_VOXELS_FILE={{logs_dir}}/ndt_cuda_voxels.json \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Run CUDA with profiling only (minimal overhead timing data)
# Saves to dated directory: logs/profiling/YYYY-MM-DD_HHMMSS/
run-cuda-profiling log_dir="": build-cuda-profiling
    #!/usr/bin/env bash
    set -e
    if [[ -z "{{log_dir}}" ]]; then
        LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
    else
        LOG_DIR="{{log_dir}}"
        mkdir -p "$LOG_DIR"
    fi
    echo "Profiling output: $LOG_DIR"
    NDT_DEBUG_FILE="$LOG_DIR/ndt_cuda_profiling.jsonl" \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"
    echo "CUDA profiling saved to: $LOG_DIR/ndt_cuda_profiling.jsonl"

# Run Autoware with profiling (timing data for comparison)
# Saves to dated directory: logs/profiling/YYYY-MM-DD_HHMMSS/
run-builtin-profiling log_dir="":
    #!/usr/bin/env bash
    set -e
    if [[ -z "{{log_dir}}" ]]; then
        # Use latest if exists, otherwise create new
        if [[ -L "{{logs_dir}}/profiling/latest" ]]; then
            LOG_DIR=$(readlink -f "{{logs_dir}}/profiling/latest")
        else
            LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
        fi
    else
        LOG_DIR="{{log_dir}}"
        mkdir -p "$LOG_DIR"
    fi
    echo "Profiling output: $LOG_DIR"
    NDT_DEBUG=1 \
    NDT_DEBUG_FILE="$LOG_DIR/ndt_autoware_profiling.jsonl" \
        ./scripts/run_demo.sh \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"
    echo "Autoware profiling saved to: $LOG_DIR/ndt_autoware_profiling.jsonl"

# Compare CUDA and Autoware profiling results (analyzes latest by default)
compare-profiling log_dir="":
    #!/usr/bin/env bash
    if [[ -z "{{log_dir}}" ]]; then
        python3 scripts/profile_ndt_comparison.py
    else
        python3 scripts/profile_ndt_comparison.py "{{log_dir}}"
    fi

# Full profiling comparison: build, run both implementations, analyze results
# Creates dated directory: logs/profiling/YYYY-MM-DD_HHMMSS/ with 'latest' symlink
profile-compare: build-cuda-profiling build-cuda-debug
    #!/usr/bin/env bash
    set -e

    # Create dated log directory
    LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
    echo "============================================================"
    echo " NDT Profiling Comparison"
    echo " Output directory: $LOG_DIR"
    echo "============================================================"

    echo ""
    echo "=== Step 1/4: Running CUDA (release/profiling build) ==="
    NDT_DEBUG_FILE="$LOG_DIR/ndt_cuda_profiling.jsonl" \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    echo ""
    echo "=== Step 2/4: Running Autoware (release build) ==="
    NDT_DEBUG=1 \
    NDT_DEBUG_FILE="$LOG_DIR/ndt_autoware_profiling.jsonl" \
        ./scripts/run_demo.sh \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    echo ""
    echo "=== Step 3/4: Running CUDA (debug build for overhead analysis) ==="
    NDT_DEBUG_FILE="$LOG_DIR/ndt_cuda_debug.jsonl" \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    echo ""
    echo "=== Step 4/4: Analyzing results ==="
    python3 scripts/profile_ndt_comparison.py "$LOG_DIR"

    echo ""
    echo "============================================================"
    echo " Profiling complete!"
    echo " Results: $LOG_DIR"
    echo " Latest:  {{logs_dir}}/profiling/latest -> $(basename $LOG_DIR)"
    echo "============================================================"

# Quick profiling: run release builds only (faster, no debug overhead analysis)
profile-quick: build-cuda-profiling
    #!/usr/bin/env bash
    set -e

    # Create dated log directory
    LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
    echo "============================================================"
    echo " Quick NDT Profiling (release builds only)"
    echo " Output directory: $LOG_DIR"
    echo "============================================================"

    echo ""
    echo "=== Step 1/3: Running CUDA (release build) ==="
    NDT_DEBUG_FILE="$LOG_DIR/ndt_cuda_profiling.jsonl" \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    echo ""
    echo "=== Step 2/3: Running Autoware (release build) ==="
    NDT_DEBUG=1 \
    NDT_DEBUG_FILE="$LOG_DIR/ndt_autoware_profiling.jsonl" \
        ./scripts/run_demo.sh \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    echo ""
    echo "=== Step 3/3: Analyzing results ==="
    python3 scripts/profile_ndt_comparison.py "$LOG_DIR"

    echo ""
    echo "============================================================"
    echo " Profiling complete!"
    echo " Results: $LOG_DIR"
    echo " Latest:  {{logs_dir}}/profiling/latest"
    echo "============================================================"

# Run Autoware with per-iteration debug output (requires build-comparison first)
run-builtin-debug:
    cd tests/comparison && just run-debug

# === Init Pose Profiling ===

# Run CUDA with init mode (Monte Carlo pose initialization)
run-cuda-init log_dir="": build-cuda-profiling
    #!/usr/bin/env bash
    set -e
    if [[ -z "{{log_dir}}" ]]; then
        LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
    else
        LOG_DIR="{{log_dir}}"
        mkdir -p "$LOG_DIR"
    fi
    echo "Init profiling output: $LOG_DIR"
    NDT_DEBUG_FILE="$LOG_DIR/ndt_cuda_profiling.jsonl" \
        ./scripts/run_demo.sh --cuda --init-mode \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"
    echo "CUDA init profiling saved to: $LOG_DIR/ndt_cuda_profiling.jsonl"

# Run Autoware with init mode (Monte Carlo pose initialization)
run-builtin-init log_dir="":
    #!/usr/bin/env bash
    set -e
    if [[ -z "{{log_dir}}" ]]; then
        if [[ -L "{{logs_dir}}/profiling/latest" ]]; then
            LOG_DIR=$(readlink -f "{{logs_dir}}/profiling/latest")
        else
            LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
        fi
    else
        LOG_DIR="{{log_dir}}"
        mkdir -p "$LOG_DIR"
    fi
    echo "Init profiling output: $LOG_DIR"
    NDT_DEBUG=1 \
    NDT_DEBUG_FILE="$LOG_DIR/ndt_autoware_profiling.jsonl" \
        ./scripts/run_demo.sh --init-mode \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"
    echo "Autoware init profiling saved to: $LOG_DIR/ndt_autoware_profiling.jsonl"

# Profile init pose: run both CUDA and Autoware with Monte Carlo initialization
profile-init: build-cuda-profiling
    #!/usr/bin/env bash
    set -e

    # Create dated log directory
    LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
    echo "============================================================"
    echo " NDT Init Pose Profiling"
    echo " Output directory: $LOG_DIR"
    echo "============================================================"

    echo ""
    echo "=== Step 1/4: Running CUDA with init mode ==="
    NDT_DEBUG_FILE="$LOG_DIR/ndt_cuda_profiling.jsonl" \
        ./scripts/run_demo.sh --cuda --init-mode \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    # Find the latest CUDA rosbag
    CUDA_ROSBAG=$(ls -td {{rosbag_output_dir}}/cuda_* 2>/dev/null | head -1)
    echo "CUDA rosbag: $CUDA_ROSBAG"

    echo ""
    echo "=== Step 2/4: Running Autoware with init mode ==="
    NDT_DEBUG=1 \
    NDT_DEBUG_FILE="$LOG_DIR/ndt_autoware_profiling.jsonl" \
        ./scripts/run_demo.sh --init-mode \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    # Find the latest Autoware rosbag
    AUTOWARE_ROSBAG=$(ls -td {{rosbag_output_dir}}/builtin_* 2>/dev/null | head -1)
    echo "Autoware rosbag: $AUTOWARE_ROSBAG"

    echo ""
    echo "=== Step 3/4: Analyzing timing results ==="
    python3 scripts/profile_ndt_comparison.py "$LOG_DIR"

    echo ""
    echo "=== Step 4/4: Comparing init poses from rosbags ==="
    if [[ -n "$CUDA_ROSBAG" && -n "$AUTOWARE_ROSBAG" ]]; then
        source /opt/autoware/1.5.0/setup.bash
        python3 scripts/compare_init_poses.py "$CUDA_ROSBAG" "$AUTOWARE_ROSBAG" \
            --output "$LOG_DIR/init_pose_comparison.txt"
        cat "$LOG_DIR/init_pose_comparison.txt"
    else
        echo "Warning: Could not find rosbags for pose comparison"
    fi

    echo ""
    echo "============================================================"
    echo " Init profiling complete!"
    echo " Results: $LOG_DIR"
    echo " Latest:  {{logs_dir}}/profiling/latest"
    echo "============================================================"

# Compare init poses from rosbag recordings
compare-init-poses cuda_rosbag autoware_rosbag:
    #!/usr/bin/env bash
    source /opt/autoware/1.5.0/setup.bash
    python3 scripts/compare_init_poses.py "{{cuda_rosbag}}" "{{autoware_rosbag}}"

# Compare init poses from latest rosbags
compare-init-poses-latest:
    #!/usr/bin/env bash
    set -e
    CUDA_ROSBAG=$(ls -td {{rosbag_output_dir}}/cuda_* 2>/dev/null | head -1)
    AUTOWARE_ROSBAG=$(ls -td {{rosbag_output_dir}}/builtin_* 2>/dev/null | head -1)
    if [[ -z "$CUDA_ROSBAG" || -z "$AUTOWARE_ROSBAG" ]]; then
        echo "Error: Could not find rosbags in {{rosbag_output_dir}}"
        echo "  CUDA: $CUDA_ROSBAG"
        echo "  Autoware: $AUTOWARE_ROSBAG"
        exit 1
    fi
    echo "CUDA rosbag: $CUDA_ROSBAG"
    echo "Autoware rosbag: $AUTOWARE_ROSBAG"
    source /opt/autoware/1.5.0/setup.bash
    python3 scripts/compare_init_poses.py "$CUDA_ROSBAG" "$AUTOWARE_ROSBAG"

# Dump voxel grid data for comparison (CUDA)
dump-voxels-cuda: build-cuda-debug-voxels
    mkdir -p {{logs_dir}}
    NDT_DUMP_VOXELS_FILE={{logs_dir}}/ndt_cuda_voxels.json \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

# Dump voxel grid data for comparison (Autoware, requires build-comparison first)
dump-voxels-autoware:
    cd tests/comparison && just dump-voxels

# Compare voxel grids between CUDA and Autoware
compare-voxels:
    python3 tmp/compare_voxels.py \
        {{logs_dir}}/ndt_cuda_voxels.json \
        {{logs_dir}}/ndt_autoware_voxels.json

# === Debug Analysis ===

# Analyze CUDA debug output
analyze-debug-cuda:
    python3 tmp/analyze_debug.py {{logs_dir}}/ndt_cuda_debug.jsonl

# Analyze Autoware debug output
analyze-debug-autoware:
    cd tests/comparison && just analyze-debug

# Analyze Autoware per-iteration debug output
analyze-iterations-autoware:
    cd tests/comparison && just analyze-iterations

# Analyze debug output from a specific file
analyze-debug file:
    python3 tmp/analyze_debug.py {{file}}

# === Accuracy Comparison (CUDA vs Autoware) ===

# Compare poses from existing profiling logs
compare-poses:
    python3 scripts/compare_poses.py \
        {{logs_dir}}/ndt_cuda_profiling.jsonl \
        {{logs_dir}}/ndt_autoware_profiling.jsonl

# Compare poses with verbose output (shows largest differences)
compare-poses-verbose:
    python3 scripts/compare_poses.py -v \
        {{logs_dir}}/ndt_cuda_profiling.jsonl \
        {{logs_dir}}/ndt_autoware_profiling.jsonl

# Full accuracy test: run both implementations and compare poses
accuracy-test: build-cuda-profiling
    #!/usr/bin/env bash
    set -e
    echo "=== Running CUDA NDT ==="
    mkdir -p {{logs_dir}}
    NDT_DEBUG_FILE={{logs_dir}}/ndt_cuda_profiling.jsonl \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}"

    echo ""
    echo "=== Running Autoware NDT ==="
    cd tests/comparison && just run-profiling

    echo ""
    echo "=== Comparing Poses ==="
    python3 scripts/compare_poses.py -v \
        {{logs_dir}}/ndt_cuda_profiling.jsonl \
        {{logs_dir}}/ndt_autoware_profiling.jsonl

# Compare poses and output JSON (for CI/automated tests)
compare-poses-json:
    python3 scripts/compare_poses.py --json \
        {{logs_dir}}/ndt_cuda_profiling.jsonl \
        {{logs_dir}}/ndt_autoware_profiling.jsonl

# === Resource Usage Profiling ===

# Analyze resource usage from latest play_log runs
analyze-resource:
    python3 scripts/analyze_resource_usage.py --latest

# Analyze resource usage from specific play_log directories
analyze-resource-dirs cuda_dir autoware_dir:
    python3 scripts/analyze_resource_usage.py \
        --cuda "{{cuda_dir}}" \
        --autoware "{{autoware_dir}}"

# Profile with tegrastats (GPU monitoring)
profile-resource: build-cuda-profiling
    #!/usr/bin/env bash
    set -e

    # Create dated log directory
    LOG_DIR=$(python3 scripts/profile_ndt_comparison.py --create-dir)
    echo "============================================================"
    echo " NDT Resource Profiling (with tegrastats)"
    echo " Output directory: $LOG_DIR"
    echo "============================================================"

    # Kill any existing tegrastats
    pkill -9 tegrastats 2>/dev/null || true
    sleep 0.5

    echo ""
    echo "=== Step 1/4: Running CUDA with tegrastats ==="
    tegrastats --interval 500 > "$LOG_DIR/cuda_tegrastats.log" 2>&1 &
    TEGRA_PID=$!
    sleep 1

    NDT_DEBUG_FILE="$LOG_DIR/ndt_cuda_profiling.jsonl" \
        ./scripts/run_demo.sh --cuda \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}" || true

    kill $TEGRA_PID 2>/dev/null || true
    sleep 1

    # Copy play_log metrics
    CUDA_PLAY_LOG=$(ls -td play_log/2026-* 2>/dev/null | head -1)
    if [[ -n "$CUDA_PLAY_LOG" ]]; then
        cp "$CUDA_PLAY_LOG/node/ndt_scan_matcher/metrics.csv" "$LOG_DIR/cuda_metrics.csv" 2>/dev/null || true
        echo "CUDA play_log: $CUDA_PLAY_LOG"
    fi

    echo ""
    echo "=== Step 2/4: Running Autoware with tegrastats ==="
    tegrastats --interval 500 > "$LOG_DIR/autoware_tegrastats.log" 2>&1 &
    TEGRA_PID=$!
    sleep 1

    NDT_DEBUG=1 \
    NDT_DEBUG_FILE="$LOG_DIR/ndt_autoware_profiling.jsonl" \
        ./scripts/run_demo.sh \
            "$(realpath {{sample_map_dir}})" \
            "$(realpath {{sample_rosbag}})" \
            "{{rosbag_output_dir}}" || true

    kill $TEGRA_PID 2>/dev/null || true
    sleep 1

    # Copy play_log metrics
    AUTOWARE_PLAY_LOG=$(ls -td play_log/2026-* 2>/dev/null | head -1)
    if [[ -n "$AUTOWARE_PLAY_LOG" ]]; then
        cp "$AUTOWARE_PLAY_LOG/node/ndt_scan_matcher/metrics.csv" "$LOG_DIR/autoware_metrics.csv" 2>/dev/null || true
        echo "Autoware play_log: $AUTOWARE_PLAY_LOG"
    fi

    echo ""
    echo "=== Step 3/4: Analyzing timing results ==="
    python3 scripts/profile_ndt_comparison.py "$LOG_DIR"

    echo ""
    echo "=== Step 4/4: Analyzing resource usage ==="
    # Create temporary directories with the metrics for analysis
    mkdir -p "$LOG_DIR/cuda_run/node/ndt_scan_matcher"
    mkdir -p "$LOG_DIR/autoware_run/node/ndt_scan_matcher"

    if [[ -f "$LOG_DIR/cuda_metrics.csv" ]]; then
        cp "$LOG_DIR/cuda_metrics.csv" "$LOG_DIR/cuda_run/node/ndt_scan_matcher/metrics.csv"
        echo "cuda_ndt_matcher" > "$LOG_DIR/cuda_run/node/ndt_scan_matcher/cmdline"
    fi
    if [[ -f "$LOG_DIR/autoware_metrics.csv" ]]; then
        cp "$LOG_DIR/autoware_metrics.csv" "$LOG_DIR/autoware_run/node/ndt_scan_matcher/metrics.csv"
        echo "autoware_ndt_scan_matcher" > "$LOG_DIR/autoware_run/node/ndt_scan_matcher/cmdline"
    fi

    # Copy tegrastats logs
    cp "$LOG_DIR/cuda_tegrastats.log" "$LOG_DIR/cuda_run/tegrastats.log" 2>/dev/null || true
    cp "$LOG_DIR/autoware_tegrastats.log" "$LOG_DIR/autoware_run/tegrastats.log" 2>/dev/null || true

    python3 scripts/analyze_resource_usage.py \
        --cuda "$LOG_DIR/cuda_run" \
        --autoware "$LOG_DIR/autoware_run"

    # Save resource analysis to file
    python3 scripts/analyze_resource_usage.py \
        --cuda "$LOG_DIR/cuda_run" \
        --autoware "$LOG_DIR/autoware_run" > "$LOG_DIR/resource_comparison.txt"

    echo ""
    echo "============================================================"
    echo " Resource profiling complete!"
    echo " Results: $LOG_DIR"
    echo " - cuda_tegrastats.log     GPU/power during CUDA run"
    echo " - autoware_tegrastats.log GPU/power during Autoware run"
    echo " - resource_comparison.txt Summary comparison"
    echo "============================================================"
