# CUDA NDT Matcher - Build System

# Cargo config generated by colcon-cargo-ros2
cargo_config := "build/ros2_cargo_config.toml"
manifest := "src/Cargo.toml"

# Build all packages
build:
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --cargo-args --release

# Clean build artifacts
clean:
    rm -rf build install log src/target

# Format code
format:
    cargo +nightly fmt --manifest-path {{manifest}}

# Lint code
lint:
    cargo +nightly fmt --check --manifest-path {{manifest}}
    cargo clippy --manifest-path {{manifest}} --config {{cargo_config}} --all-targets

# Run tests
test:
    cargo test --manifest-path {{manifest}} --config {{cargo_config}} --all-targets

# Run all quality checks (format, lint, test)
quality: lint test
